# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-python-qt-binding
  version: 0.4.6
source:
  git: https://github.com/ros-gbp/python_qt_binding-release.git
  tag: release/noetic/python_qt_binding/0.4.6-1
  target_directory: ros-noetic-python-qt-binding/src/work
  patches:
    - patch/ros-noetic-python-qt-binding.patch
    - patch/ros-noetic-python-qt-binding.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 24
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/python_qt_binding
  license: BSD-3-Clause
  summary: "This stack provides Python bindings for Qt. There are two providers: pyside and pyqt. PySide is released under the LGPL. PyQt is released under the GPL. Both the bindings and tools to build bindings are included from each available provider. For PySide, it is called &quot;Shiboken&quot;. For PyQt, this is called &quot;SIP&quot;. Also provided is adapter code to make the user's Python code independent of which binding provider was actually used which makes it very easy to switch between these."
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - pyqt-builder
    - pyqt5-sip
    - sip
    - if: build_platform != target_platform
      then:
        - qt-main
    - if: build_platform != target_platform
      then:
        - pyqt-builder
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - pyqt
    - python
    - qt-main
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-catkin
    - ros-noetic-rosbuild
    - sip
    - if: build_platform == target_platform
      then:
        - pyqt-builder
  run:
    - adwaita-icon-theme
    - pyqt
    - pyqt-builder
    - python
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-catkin
