# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-roscpp
  version: 1.17.4
source:
  git: https://github.com/ros-gbp/ros_comm-release.git
  tag: release/noetic/roscpp/1.17.4-1
  target_directory: ros-noetic-roscpp/src/work
  patches:
    - patch/ros-noetic-roscpp.patch
    - patch/ros-noetic-roscpp.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 24
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/roscpp
  license: BSD-3-Clause
  summary: roscpp is a C++ implementation of ROS. It provides a<a href="http://wiki.ros.org/Client%20Libraries">client library</a>that enables C++ programmers to quickly interface with ROS<a href="http://ros.org/wiki/Topics">Topics</a>,<a href="http://ros.org/wiki/Services">Services</a>, and<a href="http://ros.org/wiki/Parameter Server">Parameters</a>. roscpp is the most widely used ROS client library and is designed to be the high-performance library for ROS.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - libboost-devel
    - numpy
    - pip
    - pkg-config
    - python
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-catkin
    - ros-noetic-cpp-common
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-rosconsole
    - ros-noetic-roscpp-serialization
    - ros-noetic-roscpp-traits
    - ros-noetic-rosgraph-msgs
    - ros-noetic-roslang
    - ros-noetic-rostime
    - ros-noetic-std-msgs
    - ros-noetic-xmlrpcpp
  run:
    - libboost-devel
    - python
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-cpp-common
    - ros-noetic-message-runtime
    - ros-noetic-rosconsole
    - ros-noetic-roscpp-serialization
    - ros-noetic-roscpp-traits
    - ros-noetic-rosgraph-msgs
    - ros-noetic-rostime
    - ros-noetic-std-msgs
    - ros-noetic-xmlrpcpp
