# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-rqt-reconfigure
  version: 0.5.7
source:
  git: https://github.com/ros-gbp/rqt_reconfigure-release.git
  tag: release/noetic/rqt_reconfigure/0.5.7-1
  target_directory: ros-noetic-rqt-reconfigure/src/work

build:
  script: ${{ '$RECIPE_DIR/build_catkin.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_catkin.bat' }}
  number: 24
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://wiki.ros.org/rqt_reconfigure
  repository: https://github.com/ros-visualization/rqt_reconfigure
  license: BSD-3-Clause
  summary: This rqt plugin succeeds former dynamic_reconfigure's GUI (reconfigure_gui), and provides the way to view and edit the parameters that are accessible via dynamic_reconfigure.<br/><br/>(12/27/2012) In the future, arbitrary parameters that are not associated with any nodes (which are not handled by dynamic_reconfigure) might become handled. However, currently as the name indicates, this pkg solely is dependent on dynamic_reconfigure that allows access to only those params latched to nodes.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-catkin
    - ros-noetic-roslint
    - ros-noetic-rostest
    - setuptools
  run:
    - python
    - pyyaml
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-python-qt-binding
    - ros-noetic-rospy
    - ros-noetic-rqt-console
    - ros-noetic-rqt-gui
    - ros-noetic-rqt-gui-py
    - ros-noetic-rqt-py-common
