# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-noetic-draco
  version: 1.5.7

build:
  number: 24
  script: ''
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://google.github.io/draco/
  license: Apache-2.0
  summary: Draco is a library for compressing and decompressing 3D geometric meshes and point clouds. It is intended to improve the storage and transmission of 3D graphics.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build: []
  host:
    - python
    - ros-distro-mutex 0.7.* noetic_*
  run:
    - draco >=1.5.7, <1.5.8a0
    - python
    - ros-distro-mutex 0.7.* noetic_*
    - ros-noetic-catkin
